import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Anton } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ConditionalPlayer from "./components/ConditionalPlayer";
import { PlayerProvider } from "./context/PlayerContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "700", "800", "900"],
});

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${anton.variable} antialiased`}
      >
        <Script src="https://cdn.jsdelivr.net/npm/@tailwindplus/elements@1" strategy="beforeInteractive" />
        <PlayerProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
          <ConditionalPlayer />
        </PlayerProvider>
      </body>
    </html>
  );
}
